### ISSUE TITLE
Two-Year Anniversary Milestone

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#219]
I want to do a giveaway or something to mark two years of TMI in ~December. I have a few things that have been bugging me before that though:

Core features:
- [x] Finish PrusaPrinters (almost done)
- [x] Get a new logo
- [ ] Paginate /Creators/Browse
- [ ] Make some sort of tagging leaderboard
- [x] Fix the stupid loading spinner gif
- [ ] Paginate /Creators/Details
- [ ] Add number of tags to pending Minis in /Creators/Details

Database Cleanliness:
- [x] Clean-up duplicate creators
- [x] Categorize all existing tags
- [x] Go through creators and ensure Patreons are linked
- [x] Go through STLTop and look for new creators
- [x] Refresh Manuel's beastiary

Secondary Database stuff
- [ ] Clean-up "Monster" tag
- [ ] Merge synonyms when possible
- [ ] armored / armoured
- [ ] caster / spellcaster
- [ ] eldarin / eladrin
- [ ] capybarya and yoglith spaces

Ease of use:
- [x] Clean-up admin view of Mini Edit page to make tag categories clearer
- [x] Clean-up tag approval view to remove pending Minis
- [x] Better (and easier to find) guidelines for good and bad tagging. MORE TAGS != GOOD TAGS
- [x] Document overview of approval process. Unindexed -> Pending -> Approved and what it takes for each step
- [x] Fix weird JavaScript scrolling bug when adding tags
